// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:36a1674e-9023-41f2-a38b-7e7eaa3e286c",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_JPxmo5CIL",
    "aws_user_pools_web_client_id": "3sp0vc59sr0j11911eth9btt13",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://3xcxbsu25rcsbik4axxdcr6h2i.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
